#Source: https://community.home-assistant.io/t/zwavejs-aeon-labs-aeotec-zw130-wallmote-quad-all-scenes-supported/290685
blueprint:
  name: ZWaveJS - Aeotec WallMote Quad scene controller
  description: |
    Perform actions when Aeotec WallMote Quad buttons are interacted with.
    
    The release action is equivalent to a long tap.

    A release action is always triggered after a hold action, which makes
    them a bit tricky to use. The hold action is repeated as long as the
    button is held down.

  domain: automation
  input:
    zwavejs_device:
      name: ZWaveJS Device
      description: The Aeotec WallMote Quad controller to listen for events on.
      selector:
        device:
          integration: zwave_js
          manufacturer: AEON Labs
          model: ZW130
    tap_top_left_actions:
      name: Tap Top Left Actions
      selector:
        action:
      default: []
    tap_top_right_actions:
      name: Tap Top Right Actions
      selector:
        action:
      default: []
    tap_bottom_left_actions:
      name: Tap Bottom Left Actions
      selector:
        action:
      default: []
    tap_bottom_right_actions:
      name: Tap Bottom Right Actions
      selector:
        action:
      default: []
    release_top_left_actions:
      name: Release Top Left Actions
      selector:
        action:
      default: []
    release_top_right_actions:
      name: Release Top Right Actions
      selector:
        action:
      default: []
    release_bottom_left_actions:
      name: Release Bottom Left Actions
      selector:
        action:
      default: []
    release_bottom_right_actions:
      name: Release Bottom Right Actions
      selector:
        action:
      default: []
    hold_top_left_actions:
      name: Hold Top Left Actions
      selector:
        action:
      default: []
    hold_top_right_actions:
      name: Hold Top Right Actions
      selector:
        action:
      default: []
    hold_bottom_left_actions:
      name: Hold Bottom Left Actions
      selector:
        action:
      default: []
    hold_bottom_right_actions:
      name: Hold Bottom Right Actions
      selector:
        action:
      default: []

mode: single
